# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 313d8d2dfbf760da9890db5257143ace709059c199cdce411a272734bafda037fc656b1cd92237379f805b0da880492cec492e8689cc30306312cfbe7dc0503b

test:
  secret_key_base: 8f47298431ccf6e13015e5b5b7386c36847b51abeab72e8f4f5b2cf4bbd6984a03601e1d656da55da75fa1e6543947fcaea7d1d7af69f612c722d2d704f34ee8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
